version: '3'
services:
  flexilearnoj-backend-gateway:
    container_name: flexilearnoj-backend-gateway
    build:
      context: ./flexilearnoj-backend-gateway
      dockerfile: Dockerfile
    ports:
      - "8101:8101"
    networks:
      - mynetwork

  flexilearnoj-backend-user-service:
    container_name: flexilearnoj-backend-user-service
    build:
      context: ./flexilearnoj-backend-user-service
      dockerfile: Dockerfile
    ports:
      - "8102:8102"
    networks:
      - mynetwork
    depends_on:
      - flexilearnoj-backend-gateway

  flexilearnoj-backend-question-service:
    container_name: flexilearnoj-backend-question-service
    build:
      context: ./flexilearnoj-backend-question-service
      dockerfile: Dockerfile
    ports:
      - "8103:8103"
    networks:
      - mynetwork
    depends_on:
      - flexilearnoj-backend-user-service
      - flexilearnoj-backend-gateway

  flexilearnoj-backend-judge-service:
    container_name: flexilearnoj-backend-judge-service
    build:
      context: ./flexilearnoj-backend-judge-service
      dockerfile: Dockerfile
    ports:
      - "8104:8104"
    networks:
      - mynetwork
    depends_on:
      - flexilearnoj-backend-user-service
      - flexilearnoj-backend-question-service
      - flexilearnoj-backend-gateway

  flexilearnoj-backend-post-service:
    container_name: flexilearnoj-backend-post-service
    build:
      context: ./flexilearnoj-backend-post-service
      dockerfile: Dockerfile
    ports:
      - "8105:8105"
    networks:
      - mynetwork
    depends_on:
      - flexilearnoj-backend-user-service
      - flexilearnoj-backend-question-service
      - flexilearnoj-backend-gateway
      - flexilearnoj-backend-judge-service

# 网络，不定义的话就是默认网络
networks:
  mynetwork:
